---
title: "Exploratory Analysis"
output: html_document
date: "2022-12-14"
editor_options: 
  chunk_output_type: console
---

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(GGally)
library(gtsummary)
```

```{r}
df_body_fat <- read_excel("body_density_data.xlsx") %>%
  select(-id)
```

Check for and remove 0 body fat entry:
```{r}
to_remove = 
  df_body_fat %>%
  filter(bodyfat_brozek == 0 | bodyfat_siri == 0 | body_density == 0)

df_body_fat = anti_join(df_body_fat, to_remove)
```


Summary table
```{r}
summary_table = 
  df_body_fat %>%
  gtsummary::tbl_summary() %>%
  gtsummary::bold_labels()

gt::gtsave(as_gt(summary_table), file = file.path("./plots/summary_table.png"))

summary_table
```


Plot scatter plots between each pair variables, destiny plots for each variable, and correlation between each pair variables
```{r fig.width=14, fig.height=14}
df_body_fat %>%
  select(-bodyfat_siri, -body_density) %>%
  ggpairs() +
  labs(caption = "Fig1: Distributions for each Variable and Pairwise Relationship between each pair of Variables") +
  theme(plot.caption = element_text(size = 20),
        plot.caption.position = "plot")

ggsave("./plots/bodyfat_brozek_pairs.png", width = 14, height = 14)
```

```{r fig.width=12, fig.height=12}
df_body_fat %>%
  select(-bodyfat_brozek, -body_density) %>%
  ggpairs()

ggsave("./plots/bodyfat_siri_pairs.png", width = 14, height = 14)
```

```{r fig.width=12, fig.height=12}
df_body_fat %>%
  select(-bodyfat_brozek, -bodyfat_siri) %>%
  ggpairs()

ggsave("./plots/body_density_pairs.png", width = 14, height = 14)
```
All symmetric, no transformation needed. All predictors correlated with body fat.