---
title: "Final Project Raw Code"
author: "Yixuan Jiao, Landi Guo, Fengdi Zhang"
date: "2022-12-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(readxl)
library(tidyverse)
library(leaps)
library(glmnet)
library(corrplot)
library(caret)
library(MASS)
library(car)
library(interactions)

select <- dplyr::select
```

# Load data
```{r}
df_body_fat <- read_excel("body_density_data.xlsx") %>%
  select(-id,-bodyfat_siri,-body_density) %>%
  filter(bodyfat_brozek > 0)
```
# Check normality of outcomes

## Histogram
```{r}
df_body_fat %>%
  ggplot(aes(x = bodyfat_brozek)) +
  geom_histogram() +
  theme_bw() +
  labs(title = "Distribution of Bodyfat Index Computed by Brozek equation",
       x = "Bodyfat Index Computed by Brozek equation",
       y = "Count")
```
## Shapiro Test
```{r}
shapiro.test(df_body_fat$bodyfat_brozek)
```
# Check collinearity
```{r}
mult.fit <- lm(bodyfat_brozek ~ .,data = df_body_fat)

vif_values <- vif(mult.fit)
v_names <- str_to_title (names(vif_values))
vif_df <- 
  tibble(variable = v_names, vif = vif_values) %>%
  mutate(variable = fct_reorder(variable,vif))

ggplot(data = vif_df,aes(y = variable, x = vif_values)) +
  geom_col() +
  geom_vline(xintercept = 5,colour="red",linetype = "longdash") +
  theme_bw() +
  labs(x = "VIF Value",
       y = "Variable",
       title = "VIF Value of Predictors")
```
# Refit after delete correlated variables
```{r}
#filter out high vif variable.
df_body_fat <-
  df_body_fat %>%
  select(-weight,-chest,-hip,-thigh)
mult.fit <- lm(bodyfat_brozek ~ .,data = df_body_fat)

vif_values <- vif(mult.fit)
v_names <- str_to_title (names(vif_values))
vif_df <- 
  tibble(variable = v_names, vif = vif_values) %>%
  mutate(variable = fct_reorder(variable,vif))

ggplot(data = vif_df,aes(y = variable, x = vif_values)) +
  geom_col() +
  geom_vline(xintercept = 5,colour="red",linetype = "longdash") +
  theme_bw() +
  labs(x = "VIF Value",
       y = "Variable",
       title = "VIF Value After Removing Highly Correlated Predictors")

```


# Automatic Procedure
```{r}
stepwise.fit <- step(mult.fit, direction='both',trace = FALSE)
summary(stepwise.fit) %>% broom::tidy() %>% knitr::kable(digits = c(5,2,2,2), "latex")
```
# Criterion Base
```{r}
mat <- as.matrix(df_body_fat)
leaps(x = mat[,c(-1)] , y = mat[,1], nbest = 1, method = "Cp")
```

```{r}
leaps(x = mat[,c(-1)] , y = mat[,1], nbest = 1, method = "adjr2")
```

```{r}
rs <- regsubsets(bodyfat_brozek ~ ., data = df_body_fat, nbest = 1) %>% summary()
```

```{r}
par(mfrow = c(1,2))
plot(2:9, rs$cp, xlab="# of parameters", ylab="Cp Statistic")
abline(0,1)
plot(2:9, rs$adjr2, xlab="# of parameters", ylab="Adj R2")
```
# Lasso and Ridge
```{r}
lambda_seq <- 10^seq(-3, 0, by = .1)
set.seed(14)
cv_object <- cv.glmnet(as.matrix(df_body_fat[c(-1)]), df_body_fat$bodyfat_brozek,
lambda = lambda_seq, nfolds = 5)
cv_object
```

```{r}
highlight_lamda <- 
  tibble(lambda = cv_object$lambda,
mean_cv_error = cv_object$cvm) %>%
  arrange(mean_cv_error)


tibble(lambda = cv_object$lambda,
mean_cv_error = cv_object$cvm) %>%
ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() + 
  geom_point(data = highlight_lamda[1,], aes(x = lambda, y = mean_cv_error, color = 'red')) +
  labs(x = "Lambda",
       y = "Mean CV Error",
       title = "Lambda vs. Mean CV Error") +
  theme_bw()
  
```

```{r}
lasso_fit <- glmnet(as.matrix(df_body_fat[c(-1)]), df_body_fat$bodyfat_brozek, lambda = cv_object$lambda.min)
coef(lasso_fit)

```

```{r}
mtemp <- lm(formula = bodyfat_brozek ~ age + height + neck + abdomen + 
    forearm + wrist, data = df_body_fat)
par(mfrow = c(2,2))
plot(mtemp)
```
# Validation
```{r}
train = trainControl(method = "cv", number = 10)
model_caret = train(bodyfat_brozek ~ age + height + neck + abdomen + 
    forearm + wrist + neck:abdomen, data = df_body_fat,
trControl = train,
method = 'lm',
na.action = na.pass)
print(model_caret)
```

```{r}
inter_model <- lm(bodyfat_brozek ~ (age + height + neck + abdomen + forearm + wrist)^2, data = df_body_fat)
interact_plot(inter_model,pred = neck, modx = abdomen)
```

```{r}
interact_plot(update(stepwise.fit, . ~ . + neck*abdomen),pred = neck, modx = abdomen)
```


```{r}
aov(bodyfat_brozek ~ (age + height + neck + abdomen + forearm + wrist)^2,data = df_body_fat) %>% summary

aov(update(stepwise.fit, . ~ . + neck*abdomen)) %>% summary
```

```{r}
update(stepwise.fit, . ~ . + bicep) %>% summary
```

